/* eslint-disable */
const commonDatas = {
  moneyTypes: {
    "message":"查询成功",
    "recordsTotal":41,
    "showData":[
        {
            "currencyDesc":"人民币",
            "currencyId":1,
            "currencyName":"RMB"
        },
        {
            "currencyDesc":"美金",
            "currencyId":2,
            "currencyName":"USD"
        },
        {
            "currencyDesc":"欧元",
            "currencyId":3,
            "currencyName":"EUR"
        },
        {
            "currencyDesc":"台币",
            "currencyId":4,
            "currencyName":"NTD"
        },
        {
            "currencyDesc":"巴西币",
            "currencyId":5,
            "currencyName":"BRL"
        },
        {
            "currencyDesc":"加拿大元",
            "currencyId":6,
            "currencyName":"CAD"
        },
        {
            "currencyDesc":"瑞士法郎",
            "currencyId":7,
            "currencyName":"CHF"
        },
        {
            "currencyDesc":"捷克克朗",
            "currencyId":8,
            "currencyName":"CZK"
        },
        {
            "currencyDesc":"丹麦克朗",
            "currencyId":9,
            "currencyName":"DKK"
        },
        {
            "currencyDesc":"英镑",
            "currencyId":10,
            "currencyName":"GBP"
        },
        {
            "currencyDesc":"港元",
            "currencyId":11,
            "currencyName":"HKD"
        },
        {
            "currencyDesc":"匈牙利福林",
            "currencyId":12,
            "currencyName":"HUF"
        },
        {
            "currencyDesc":"印度卢比",
            "currencyId":13,
            "currencyName":"INR"
        },
        {
            "currencyDesc":"日元",
            "currencyId":14,
            "currencyName":"JPY"
        },
        {
            "currencyDesc":"墨西哥元",
            "currencyId":15,
            "currencyName":"MXN"
        },
        {
            "currencyDesc":"马来西亚林吉特",
            "currencyId":16,
            "currencyName":"MYR"
        },
        {
            "currencyDesc":"挪威克朗",
            "currencyId":17,
            "currencyName":"NOK"
        },
        {
            "currencyDesc":"澳大利亚元",
            "currencyId":18,
            "currencyName":"AUD"
        },
        {
            "currencyDesc":"波兰兹罗提",
            "currencyId":19,
            "currencyName":"PLN"
        },
        {
            "currencyDesc":"瑞典克朗",
            "currencyId":20,
            "currencyName":"SEK"
        },
        {
            "currencyDesc":"新加坡元",
            "currencyId":21,
            "currencyName":"SGD"
        },
        {
            "currencyDesc":"斯洛伐克克朗",
            "currencyId":22,
            "currencyName":"SKK"
        },
        {
            "currencyDesc":"泰铢",
            "currencyId":23,
            "currencyName":"THB"
        },
        {
            "currencyDesc":"越南盾",
            "currencyId":24,
            "currencyName":"VND"
        },
        {
            "currencyDesc":"迪拉姆",
            "currencyId":25,
            "currencyName":"AED"
        },
        {
            "currencyDesc":"德国马克",
            "currencyId":26,
            "currencyName":"DEM"
        },
        {
            "currencyDesc":"芬兰马克",
            "currencyId":27,
            "currencyName":"FIM"
        },
        {
            "currencyDesc":"法国法郎",
            "currencyId":28,
            "currencyName":"FRF"
        },
        {
            "currencyDesc":"印尼盾",
            "currencyId":29,
            "currencyName":"IDR"
        },
        {
            "currencyDesc":"爱尔兰镑",
            "currencyId":30,
            "currencyName":"IEP"
        },
        {
            "currencyDesc":"韩国元",
            "currencyId":31,
            "currencyName":"KRW"
        },
        {
            "currencyDesc":"荷兰盾",
            "currencyId":32,
            "currencyName":"NLG"
        },
        {
            "currencyDesc":"新西兰元",
            "currencyId":33,
            "currencyName":"NZD"
        },
        {
            "currencyDesc":"菲律宾比索",
            "currencyId":34,
            "currencyName":"PHP"
        },
        {
            "currencyDesc":"罗马尼亚列伊",
            "currencyId":35,
            "currencyName":"RON"
        },
        {
            "currencyDesc":"俄罗斯卢布",
            "currencyId":36,
            "currencyName":"RUB"
        },
        {
            "currencyDesc":"西班牙比塞塔",
            "currencyId":37,
            "currencyName":"ESP"
        },
        {
            "currencyDesc":"兰特",
            "currencyId":38,
            "currencyName":"ZAR"
        },
        {
            "currencyDesc":"比利时法郎",
            "currencyId":39,
            "currencyName":"BEF"
        },
        {
            "currencyDesc":"奥地利先令",
            "currencyId":40,
            "currencyName":"ATS"
        },
        {
            "currencyDesc":"意大利里拉",
            "currencyId":41,
            "currencyName":"ITL"
        }
    ],
    "status":1
},
  arStatus: {
    "message":"查询成功",
    "recordsTotal":14,
    "showData":[
        {
            "arStatusTypeEngName":"unconfirmed",
            "arStatusTypeId":1,
            "arStatusTypeName":"待確認"
        },
        {
            "arStatusTypeEngName":"confirmed",
            "arStatusTypeId":2,
            "arStatusTypeName":"已確認"
        },
        {
            "arStatusTypeEngName":"transfered",
            "arStatusTypeId":3,
            "arStatusTypeName":"已授讓"
        },
        {
            "arStatusTypeEngName":"reject",
            "arStatusTypeId":6,
            "arStatusTypeName":"授讓拒絕"
        },
        {
            "arStatusTypeEngName":"cancelTransfered",
            "arStatusTypeId":9,
            "arStatusTypeName":"授讓取消"
        },
        {
            "arStatusTypeEngName":"discountApplying",
            "arStatusTypeId":22,
            "arStatusTypeName":"貼現申請中"
        },
        {
            "arStatusTypeEngName":"discountSigning",
            "arStatusTypeId":23,
            "arStatusTypeName":"贴现合同簽署中"
        },
        {
            "arStatusTypeEngName":"discountAuditing",
            "arStatusTypeId":24,
            "arStatusTypeName":"放款核實"
        },
        {
            "arStatusTypeEngName":"discountNotLoaned",
            "arStatusTypeId":25,
            "arStatusTypeName":"未放款"
        },
        {
            "arStatusTypeEngName":"discountLoaned",
            "arStatusTypeId":26,
            "arStatusTypeName":"已放款"
        },
        {
            "arStatusTypeEngName":"discountCanceled",
            "arStatusTypeId":27,
            "arStatusTypeName":"貼現取消"
        },
        {
            "arStatusTypeEngName":"discountReject",
            "arStatusTypeId":28,
            "arStatusTypeName":"放款拒絕"
        },
        {
            "arStatusTypeEngName":"discountReceivable",
            "arStatusTypeId":29,
            "arStatusTypeName":"已回款"
        },
        {
            "arStatusTypeEngName":"discountDisabled",
            "arStatusTypeId":99,
            "arStatusTypeName":"不可用"
        }
    ],
    "status":1
},
 comdata:{
    result: 'true',
    message: ' 操作成功'
 },
 arDatas:{
    "aaData":[
        {
            "arStatusTypeName":"已確認",
            "billBookAmt":18406.44,
            "billBookCurr":null,
            "billDueDate":1530288000000,
            "billId":"5100002408",
            "billPayDate":null,
            "billPayStatus":null,
            "billStartDate":1520870400000,
            "buyerCustNo":null,
            "checkedStatus":2,
            "companyName":"深圳富泰宏精密工業有限公司",
            "createtime":1522359044000,
            "currencyDesc":null,
            "currencyName":null,
            "custFromId":"",
            "custFromName":"",
            "custId":"09210827048265",
            "custToId":"",
            "custToName":"",
            "discountAuditStatus":1,
            "isInterfaceMode":0,
            "isMasterAr":1,
            "isNeedDiscountAudit":0,
            "loanAmt":18406.44,
            "masterChainId":"AR20180330000003",
            "parentChainId":"",
            "tableData":[
                {
                    "arStatusTypeName":"放款拒絕",
                    "billBookAmt":1000,
                    "billBookCurr":1,
                    "billDueDate":1509465600000,
                    "billId":"HBA-H70010",
                    "billPayDate":1509811200000,
                    "billStartDate":1499443200000,
                    "buyerCustNo":"A086348",
                    "checkedStatus":23,
                    "companyName":"福士瑞精密工業(鄭州)有限公司",
                    "createtime":1505953973000,
                    "currencyDesc":"人民币",
                    "currencyName":"RMB",
                    "custFromId":"09210827048265",
                    "custFromName":"深圳市新威達電子有限公司",
                    "custId":"b4e0e5f6-f17d-4b7b-9ade-99fa8f06bac8",
                    "custToId":"b4e0e5f6-f17d-4b7b-9ade-99fa8f06bac8",
                    "custToName":"HLF",
                    "isInterfaceMode":1,
                    "isMasterAr":0,
                    "loanAmt":0,
                    "masterChainId":"AR20170921000151",
                    "parentChainId":"AR20170921000038",
                    "transSerialNo":null,
                    "transType":null,
                    "vendorCode":"b4e0e5f6-f17d-4b7b-9ade-99fa8f06bac8",
                    "vendorName":"HLF"
                }
            ],
            "transSerialNo":"",
            "transType":"",
            "vendorCode":"VCN0018154",
            "vendorName":"深圳市新威達電子有限公司"
        },
        {
            "arStatusTypeName":"已確認",
            "billBookAmt":22604.4,
            "billBookCurr":null,
            "billDueDate":1532880000000,
            "billId":"5100003429",
            "billPayDate":null,
            "billPayStatus":null,
            "billStartDate":1523548800000,
            "buyerCustNo":null,
            "checkedStatus":2,
            "companyName":"深圳富泰宏精密工業有限公司",
            "createtime":1523655348000,
            "currencyDesc":null,
            "currencyName":null,
            "custFromId":"",
            "custFromName":"",
            "custId":"09210827048265",
            "custToId":"",
            "custToName":"",
            "discountAuditStatus":1,
            "isInterfaceMode":0,
            "isMasterAr":1,
            "isNeedDiscountAudit":0,
            "loanAmt":22604.4,
            "masterChainId":"AR20180414000005",
            "parentChainId":"",
            "tableData":[

            ],
            "transSerialNo":"",
            "transType":"",
            "vendorCode":"VCN0018154",
            "vendorName":"深圳市新威達電子有限公司"
        },
        {
            "arStatusTypeName":"已確認",
            "billBookAmt":2260.44,
            "billBookCurr":null,
            "billDueDate":1522512000000,
            "billId":"5100011105",
            "billPayDate":null,
            "billPayStatus":null,
            "billStartDate":1512921600000,
            "buyerCustNo":"A086041",
            "checkedStatus":2,
            "companyName":"深圳富泰宏精密工業有限公司",
            "createtime":1513027773000,
            "currencyDesc":null,
            "currencyName":null,
            "custFromId":"",
            "custFromName":"",
            "custId":"09210827048265",
            "custToId":"",
            "custToName":"",
            "discountAuditStatus":-1,
            "isInterfaceMode":0,
            "isMasterAr":1,
            "isNeedDiscountAudit":1,
            "loanAmt":2260.44,
            "masterChainId":"AR20171212000001",
            "parentChainId":"",
            "tableData":[

            ],
            "transSerialNo":"",
            "transType":"",
            "vendorCode":"VCN0018154",
            "vendorName":"深圳市新威達電子有限公司"
        },
        {
            "arStatusTypeName":"已確認",
            "billBookAmt":7806.24,
            "billBookCurr":null,
            "billDueDate":1525190400000,
            "billId":"9300000053",
            "billPayDate":null,
            "billPayStatus":null,
            "billStartDate":1515600000000,
            "buyerCustNo":null,
            "checkedStatus":2,
            "companyName":"深圳富泰宏精密工業有限公司",
            "createtime":1515706452000,
            "currencyDesc":null,
            "currencyName":null,
            "custFromId":"",
            "custFromName":"",
            "custId":"09210827048265",
            "custToId":"",
            "custToName":"",
            "discountAuditStatus":1,
            "isInterfaceMode":0,
            "isMasterAr":1,
            "isNeedDiscountAudit":0,
            "loanAmt":7806.24,
            "masterChainId":"AR20180112000002",
            "parentChainId":"",
            "tableData":[

            ],
            "transSerialNo":"",
            "transType":"",
            "vendorCode":"VCN0018154",
            "vendorName":"深圳市新威達電子有限公司"
        },
        {
            "arStatusTypeName":"已確認",
            "billBookAmt":27927.9,
            "billBookCurr":null,
            "billDueDate":1525190400000,
            "billId":"9300000054",
            "billPayDate":null,
            "billPayStatus":null,
            "billStartDate":1515600000000,
            "buyerCustNo":null,
            "checkedStatus":2,
            "companyName":"深圳富泰宏精密工業有限公司",
            "createtime":1515706453000,
            "currencyDesc":null,
            "currencyName":null,
            "custFromId":"",
            "custFromName":"",
            "custId":"09210827048265",
            "custToId":"",
            "custToName":"",
            "discountAuditStatus":1,
            "isInterfaceMode":0,
            "isMasterAr":1,
            "isNeedDiscountAudit":0,
            "loanAmt":27927.9,
            "masterChainId":"AR20180112000003",
            "parentChainId":"",
            "tableData":[

            ],
            "transSerialNo":"",
            "transType":"",
            "vendorCode":"VCN0018154",
            "vendorName":"深圳市新威達電子有限公司"
        },
        {
            "arStatusTypeName":"已確認",
            "billBookAmt":533.52,
            "billBookCurr":null,
            "billDueDate":1525190400000,
            "billId":"9300000455",
            "billPayDate":null,
            "billPayStatus":null,
            "billStartDate":1516118400000,
            "buyerCustNo":null,
            "checkedStatus":2,
            "companyName":"深圳富泰宏精密工業有限公司",
            "createtime":1522359045000,
            "currencyDesc":null,
            "currencyName":null,
            "custFromId":"",
            "custFromName":"",
            "custId":"09210827048265",
            "custToId":"",
            "custToName":"",
            "discountAuditStatus":1,
            "isInterfaceMode":0,
            "isMasterAr":1,
            "isNeedDiscountAudit":0,
            "loanAmt":533.52,
            "masterChainId":"AR20180330000004",
            "parentChainId":"",
            "tableData":[

            ],
            "transSerialNo":"",
            "transType":"",
            "vendorCode":"VCN0018154",
            "vendorName":"深圳市新威達電子有限公司"
        },
        {
            "arStatusTypeName":"已確認",
            "billBookAmt":2134.08,
            "billBookCurr":null,
            "billDueDate":1525190400000,
            "billId":"9300000528",
            "billPayDate":null,
            "billPayStatus":null,
            "billStartDate":1516204800000,
            "buyerCustNo":null,
            "checkedStatus":2,
            "companyName":"深圳富泰宏精密工業有限公司",
            "createtime":1522359045000,
            "currencyDesc":null,
            "currencyName":null,
            "custFromId":"",
            "custFromName":"",
            "custId":"09210827048265",
            "custToId":"",
            "custToName":"",
            "discountAuditStatus":1,
            "isInterfaceMode":0,
            "isMasterAr":1,
            "isNeedDiscountAudit":0,
            "loanAmt":2134.08,
            "masterChainId":"AR20180330000005",
            "parentChainId":"",
            "tableData":[

            ],
            "transSerialNo":"",
            "transType":"",
            "vendorCode":"VCN0018154",
            "vendorName":"深圳市新威達電子有限公司"
        },
        {
            "arStatusTypeName":"已確認",
            "billBookAmt":533.52,
            "billBookCurr":null,
            "billDueDate":1527609600000,
            "billId":"9300000873",
            "billPayDate":null,
            "billPayStatus":null,
            "billStartDate":1517414400000,
            "buyerCustNo":null,
            "checkedStatus":2,
            "companyName":"深圳富泰宏精密工業有限公司",
            "createtime":1522359045000,
            "currencyDesc":null,
            "currencyName":null,
            "custFromId":"",
            "custFromName":"",
            "custId":"09210827048265",
            "custToId":"",
            "custToName":"",
            "discountAuditStatus":1,
            "isInterfaceMode":0,
            "isMasterAr":1,
            "isNeedDiscountAudit":0,
            "loanAmt":533.52,
            "masterChainId":"AR20180330000006",
            "parentChainId":"",
            "tableData":[

            ],
            "transSerialNo":"",
            "transType":"",
            "vendorCode":"VCN0018154",
            "vendorName":"深圳市新威達電子有限公司"
        },
        {
            "arStatusTypeName":"已確認",
            "billBookAmt":2134.08,
            "billBookCurr":null,
            "billDueDate":1527609600000,
            "billId":"9300000896",
            "billPayDate":null,
            "billPayStatus":null,
            "billStartDate":1517414400000,
            "buyerCustNo":null,
            "checkedStatus":2,
            "companyName":"深圳富泰宏精密工業有限公司",
            "createtime":1522359045000,
            "currencyDesc":null,
            "currencyName":null,
            "custFromId":"",
            "custFromName":"",
            "custId":"09210827048265",
            "custToId":"",
            "custToName":"",
            "discountAuditStatus":1,
            "isInterfaceMode":0,
            "isMasterAr":1,
            "isNeedDiscountAudit":0,
            "loanAmt":2134.08,
            "masterChainId":"AR20180330000007",
            "parentChainId":"",
            "tableData":[
                {
                    "arStatusTypeName":"不可用",
                    "billBookAmt":2000,
                    "billBookCurr":null,
                    "billDueDate":1527609600000,
                    "billId":"9300000896",
                    "billPayDate":null,
                    "billStartDate":1517414400000,
                    "buyerCustNo":null,
                    "checkedStatus":99,
                    "companyName":"深圳富泰宏精密工業有限公司",
                    "createtime":1527666255000,
                    "currencyDesc":null,
                    "currencyName":null,
                    "custFromId":"09210827048265",
                    "custFromName":"深圳市新威達電子有限公司",
                    "custId":"15c09de8-6600-42c5-8e5a-acfe1951f8b0",
                    "custToId":"15c09de8-6600-42c5-8e5a-acfe1951f8b0",
                    "custToName":"CF",
                    "isInterfaceMode":1,
                    "isMasterAr":0,
                    "loanAmt":0,
                    "masterChainId":"AR20180530000005",
                    "parentChainId":"AR20180330000007",
                    "transSerialNo":"63dd609c-7fd4-4f83-acc2-0a85758ae60b",
                    "transType":"discount",
                    "vendorCode":"VCN0018154",
                    "vendorName":"深圳市新威達電子有限公司"
                }
            ],
            "transSerialNo":"",
            "transType":"",
            "vendorCode":"VCN0018154",
            "vendorName":"深圳市新威達電子有限公司"
        }
    ],
    "draw":0,
    "recordsFiltered":436,
    "recordsTotal":436
},
arDetails:{
    "arAvailableAmt":3205734.73,
    "arSourceDesc":"自有",
    "arStatusTypeName":"已確認",
    "billBookAmt":3205734.73,
    "billPayDate":1527609600000,
    "checkedStatus":2,
    "companyName":"鴻富泰精密電子(煙台)有限公司",
    "contractList":[

    ],
    "currencyDesc":"美金",
    "currencyName":"USD",
    "custFromId":null,
    "custFromName":null,
    "custToId":null,
    "custToName":null,
    "invoiceCustomList":[
        {
            "invoiceAfterTaxAmt":12184.93,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517068800000,
            "invoiceIsSelected":1,
            "invoiceNo":"07008783"
        },
        {
            "invoiceAfterTaxAmt":11533.36,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517068800000,
            "invoiceIsSelected":1,
            "invoiceNo":"07008784"
        },
        {
            "invoiceAfterTaxAmt":8085.66,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517155200000,
            "invoiceIsSelected":1,
            "invoiceNo":"07008811"
        },
        {
            "invoiceAfterTaxAmt":8340.48,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517155200000,
            "invoiceIsSelected":1,
            "invoiceNo":"07008809"
        },
        {
            "invoiceAfterTaxAmt":5710.93,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517155200000,
            "invoiceIsSelected":1,
            "invoiceNo":"07008810"
        },
        {
            "invoiceAfterTaxAmt":8340.48,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517155200000,
            "invoiceIsSelected":1,
            "invoiceNo":"07008808"
        },
        {
            "invoiceAfterTaxAmt":5053.54,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517587200000,
            "invoiceIsSelected":0,
            "invoiceNo":"07008856"
        },
        {
            "invoiceAfterTaxAmt":8340.48,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517587200000,
            "invoiceIsSelected":1,
            "invoiceNo":"07008857"
        },
        {
            "invoiceAfterTaxAmt":444.31,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517587200000,
            "invoiceIsSelected":1,
            "invoiceNo":"07008864"
        },
        {
            "invoiceAfterTaxAmt":5125.94,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517587200000,
            "invoiceIsSelected":1,
            "invoiceNo":"07008860"
        },
        {
            "invoiceAfterTaxAmt":14521.99,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517587200000,
            "invoiceIsSelected":1,
            "invoiceNo":"07008858"
        },
        {
            "invoiceAfterTaxAmt":8340.48,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517587200000,
            "invoiceIsSelected":1,
            "invoiceNo":"07008861"
        },
        {
            "invoiceAfterTaxAmt":5963.87,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517587200000,
            "invoiceIsSelected":0,
            "invoiceNo":"07008865"
        },
        {
            "invoiceAfterTaxAmt":10953.94,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517587200000,
            "invoiceIsSelected":0,
            "invoiceNo":"07008867"
        },
        {
            "invoiceAfterTaxAmt":231.25,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517587200000,
            "invoiceIsSelected":0,
            "invoiceNo":"07008862"
        },
        {
            "invoiceAfterTaxAmt":10903.45,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517587200000,
            "invoiceIsSelected":0,
            "invoiceNo":"07008859"
        },
        {
            "invoiceAfterTaxAmt":9731.08,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517587200000,
            "invoiceIsSelected":0,
            "invoiceNo":"07008866"
        },
        {
            "invoiceAfterTaxAmt":1495.89,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517587200000,
            "invoiceIsSelected":0,
            "invoiceNo":"07008863"
        },
        {
            "invoiceAfterTaxAmt":11085.76,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517846400000,
            "invoiceIsSelected":0,
            "invoiceNo":"07008892"
        },
        {
            "invoiceAfterTaxAmt":10953.94,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517846400000,
            "invoiceIsSelected":0,
            "invoiceNo":"07008886"
        },
        {
            "invoiceAfterTaxAmt":8340.48,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517846400000,
            "invoiceIsSelected":0,
            "invoiceNo":"07008888"
        },
        {
            "invoiceAfterTaxAmt":15153.19,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517846400000,
            "invoiceIsSelected":0,
            "invoiceNo":"07008884"
        },
        {
            "invoiceAfterTaxAmt":724.72,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517846400000,
            "invoiceIsSelected":0,
            "invoiceNo":"07008889"
        },
        {
            "invoiceAfterTaxAmt":9204.16,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517846400000,
            "invoiceIsSelected":0,
            "invoiceNo":"07008894"
        },
        {
            "invoiceAfterTaxAmt":5927.04,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517846400000,
            "invoiceIsSelected":0,
            "invoiceNo":"07008891"
        },
        {
            "invoiceAfterTaxAmt":887.09,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517846400000,
            "invoiceIsSelected":0,
            "invoiceNo":"07008883"
        },
        {
            "invoiceAfterTaxAmt":333.9,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517846400000,
            "invoiceIsSelected":0,
            "invoiceNo":"07008887"
        },
        {
            "invoiceAfterTaxAmt":5049.42,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517846400000,
            "invoiceIsSelected":0,
            "invoiceNo":"07008885"
        },
        {
            "invoiceAfterTaxAmt":5317.83,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517846400000,
            "invoiceIsSelected":0,
            "invoiceNo":"07008890"
        },
        {
            "invoiceAfterTaxAmt":10953.94,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1517846400000,
            "invoiceIsSelected":0,
            "invoiceNo":"07008893"
        },
        {
            "invoiceAfterTaxAmt":5764.32,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519315200000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993297"
        },
        {
            "invoiceAfterTaxAmt":6257.71,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519315200000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993294"
        },
        {
            "invoiceAfterTaxAmt":9334.25,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519315200000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993298"
        },
        {
            "invoiceAfterTaxAmt":11055.25,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519315200000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993305"
        },
        {
            "invoiceAfterTaxAmt":1477.72,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519315200000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993292"
        },
        {
            "invoiceAfterTaxAmt":14974.65,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519315200000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993299"
        },
        {
            "invoiceAfterTaxAmt":16426.14,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519315200000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993293"
        },
        {
            "invoiceAfterTaxAmt":4323.24,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519315200000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993302"
        },
        {
            "invoiceAfterTaxAmt":10953.94,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519315200000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993303"
        },
        {
            "invoiceAfterTaxAmt":8829.39,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519315200000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993289"
        },
        {
            "invoiceAfterTaxAmt":16426.14,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519315200000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993300"
        },
        {
            "invoiceAfterTaxAmt":6672.38,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519315200000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993306"
        },
        {
            "invoiceAfterTaxAmt":6250.56,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519315200000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993296"
        },
        {
            "invoiceAfterTaxAmt":5764.32,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519315200000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993295"
        },
        {
            "invoiceAfterTaxAmt":15461.87,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519315200000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993291"
        },
        {
            "invoiceAfterTaxAmt":10008.58,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519315200000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993304"
        },
        {
            "invoiceAfterTaxAmt":10458.86,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519315200000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993290"
        },
        {
            "invoiceAfterTaxAmt":5576.44,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519315200000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993301"
        },
        {
            "invoiceAfterTaxAmt":2781.21,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519401600000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993347"
        },
        {
            "invoiceAfterTaxAmt":7824.24,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519401600000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993341"
        },
        {
            "invoiceAfterTaxAmt":10008.58,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519401600000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993345"
        },
        {
            "invoiceAfterTaxAmt":8340.48,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519401600000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993348"
        },
        {
            "invoiceAfterTaxAmt":640.74,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519401600000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993350"
        },
        {
            "invoiceAfterTaxAmt":5143.04,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519401600000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993342"
        },
        {
            "invoiceAfterTaxAmt":5766.68,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519401600000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993343"
        },
        {
            "invoiceAfterTaxAmt":5562.41,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519401600000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993354"
        },
        {
            "invoiceAfterTaxAmt":5764.32,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519401600000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993352"
        },
        {
            "invoiceAfterTaxAmt":1498.22,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519401600000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993351"
        },
        {
            "invoiceAfterTaxAmt":12452.09,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519401600000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993353"
        },
        {
            "invoiceAfterTaxAmt":16836.18,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519401600000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993355"
        },
        {
            "invoiceAfterTaxAmt":7154.92,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519401600000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993356"
        },
        {
            "invoiceAfterTaxAmt":10953.94,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519401600000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993346"
        },
        {
            "invoiceAfterTaxAmt":5764.32,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519401600000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993344"
        },
        {
            "invoiceAfterTaxAmt":9204.16,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519660800000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993383"
        },
        {
            "invoiceAfterTaxAmt":5927.04,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519660800000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993384"
        },
        {
            "invoiceAfterTaxAmt":2882.16,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519660800000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993385"
        },
        {
            "invoiceAfterTaxAmt":130,
            "invoiceCurrency":2,
            "invoiceCurrencyDesc":null,
            "invoiceDate":1519920000000,
            "invoiceIsSelected":0,
            "invoiceNo":"04993405"
        }
    ],
    "isAvailableInvoice":0,
    "isMasterAr":1,
    "parentChainId":null,
    "poNumber":null,
    "sourceChainId":null,
    "transSerial":null,
    "transSerialNo":null,
    "transType":null
},
factories:{
    "message":"查询成功",
    "recordsTotal":5,
    "showData":[
        {
            "factoringApId":"FJF",
            "factoringCustId":"11031049033568"
        },
        {
            "factoringApId":"富泰华04",
            "factoringCustId":"89349cc9-1768-436c-8932-a37f181a23c6"
        },
        {
            "factoringApId":"富泰华03",
            "factoringCustId":"b7a95f78-349e-4689-8b7e-1a48228fd456"
        },
        {
            "factoringApId":"HLF",
            "factoringCustId":"b4e0e5f6-f17d-4b7b-9ade-99fa8f06bac8"
        },
        {
            "factoringApId":"CF",
            "factoringCustId":"15c09de8-6600-42c5-8e5a-acfe1951f8b0"
        }
    ],
    "status":1
},
fenboList:{
    "aaData":[
        {
            "billId":"HBA-H70010",
            "buyerCustNo":"A086348",
            "companyName":"福士瑞精密工業(鄭州)有限公司",
            "companyNameOfL1":"深圳市新威達電子有限公司",
            "custFromName":"深圳市新威達電子有限公司",
            "custId":"09210827048265",
            "isAudited":0,
            "riskPlatFormURL":"https://jurongtest.foxconn.com/report",
            "riskPlatFormVendorApi":"vendor",
            "vendorCodes":"VCN0018154"
        },
        {
            "billId":"HPF-HC0057",
            "buyerCustNo":"A086471",
            "companyName":"深圳市裕展精密科技有限公司",
            "companyNameOfL1":"VCN0000152公司名稱",
            "custFromName":"VCN0000152公司名稱",
            "custId":"10200823045270",
            "isAudited":0,
            "riskPlatFormURL":"https://jurongtest.foxconn.com/report",
            "riskPlatFormVendorApi":"vendor",
            "vendorCodes":"VCN0000152"
        },
        {
            "billId":"HTT-I40375",
            "buyerCustNo":"A086350",
            "companyName":"鴻富準精密工業(深圳)有限公司",
            "companyNameOfL1":"深圳市新威達電子有限公司",
            "custFromName":null,
            "custId":"09210827048265",
            "isAudited":1,
            "riskPlatFormURL":"https://jurongtest.foxconn.com/report",
            "riskPlatFormVendorApi":"vendor",
            "vendorCodes":"VCN0018154"
        },
        {
            "billId":"HOI-HB0014",
            "buyerCustNo":"A086440",
            "companyName":"晉城富泰華精密電子有限公司",
            "companyNameOfL1":"VCN0000152公司名稱",
            "custFromName":"VCN0000152暱稱",
            "custId":"10200823045270",
            "isAudited":1,
            "riskPlatFormURL":"https://jurongtest.foxconn.com/report",
            "riskPlatFormVendorApi":"vendor",
            "vendorCodes":"VCN0000152"
        }
    ],
    "draw":2,
    "recordsFiltered":4,
    "recordsTotal":4
}
}

export default commonDatas
