/* eslint-disable */
const userInfo=
{
  "data":{
      "businessEndDate":null,
      "businessStartDate":null,
      "companyAddress":"",
      "companyAuthenticationInfo":{
          "bankName":"中国银行",
          "companyName":"",
          "isAuthened":0
      },
      "companyBusinessScope":null,
      "companyName":null,
      "companyPersonSum":null,
      "companyPhone":"1111",
      "companyRegisterDate":null,
      "contactIdcardNum":null,
      "contactMail":null,
      "contactPerson":null,
      "contactPhone":null,
      "contractAuthenticationInfo":{
          "contactMail":"12345678@163.com",
          "contactPerson":"杨林",
          "contactPhone":"15507580148",
          "isAuthened":0
      },
      "createip":null,
      "createtime":null,
      "creditCode":"",
      "custId":"15c09de8-6600-42c5-8e5a-acfe1951f8b0",
      "custNickname":null,
      "custPassword":null,
      "custType":null,
      "custUsername":null,
      "customerId":null,
      "establishDate":null,
      "identifySource":null,
      "isUsable":null,
      "isUsableDesc":"可用",
      "lastlogintime":null,
      "legalAuthenticationInfo":{
          "isAuthened":0,
          "legalMail":null,
          "legalPerson":null,
          "legalPhone":null
      },
      "legalIdcardNum":null,
      "legalMail":null,
      "legalPerson":null,
      "legalPhone":null,
      "licenseAddress":null,
      "licenseNumber":null,
      "licenseUrl":null,
      "licenseViceNumber":null,
      "licenseViceUrl":null,
      "logoUrl":null,
      "mainProducts":"",
      "modifytime":null,
      "organizationNumber":null,
      "organizationUrl":null,
      "paidinCapital":null,
      "paidinCurrencyType":null,
      "payTaxesNumber":"",
      "registeredCapital":null,
      "registeredCurrencyType":null,
      "registry":null,
      "sourceName":null,
      "taxNumber":null,
      "taxUrl":null,
      "vendorCodes":""
  },
  "msg":"返回结果正常",
  "recordsTotal":null,
  "status":1
}


export default userInfo